FROM maven:3.9-eclipse-temurin-21-alpine AS build
RUN apk add --no-cache git
RUN mkdir /builder
WORKDIR /builder
RUN git clone https://github.com/gdimitriu/transformers.git --config core.autocrlf=input
WORKDIR /builder/transformers/transformationsEngine
RUN mvn clean package

FROM eclipse-temurin:21-jre-alpine
COPY --from=build /builder/transformers/transformationsEngine/target/assembly /app
WORKDIR /app
EXPOSE 8099
ENTRYPOINT ["java"]
CMD ["-jar", "/app/bin/transformationsEngine.jar", "8099"]
