version: "3.8"
services:
    tranformationsEngine:
        image: gdimitriu/transformations-engine
        ports:
            - 8099:8099
        networks:
            - transformers-net
        environment:
            - JAVA_TOOL_OPTIONS=-XX:MaxRAMPercentage=75.0
        deploy:
            replicas: 2
            update_config:
                parallelism: 2
                delay: 10s

networks:
    transformers-net:
        driver: overlay
